# Generated by Django 5.0.6 on 2024-05-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uesc_app", "0007_cargo_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="nome",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
