# Generated by Django 5.0.6 on 2024-05-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uesc_app", "0008_alter_cargo_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(default="", max_length=11),
            preserve_default=False,
        ),
    ]
