# Generated by Django 5.0.6 on 2024-05-23 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uesc_app", "0009_usuario_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="user_ptr",
        ),
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
